import { Alert, Box, Button, CircularProgress, Container, Link, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { api, parseApiError } from '../api/client';
import { useState } from 'react';
import { PhotoGallery } from '../components/media/PhotoGallery';

export const LoginPage=()=>{const [email,setE]=useState('admin@local');const [password,setP]=useState('Admin123!');const m=useMutation({mutationFn:()=>api.post('/api/auth/login',{email,password}),onSuccess:(r)=>localStorage.setItem('token',r.data.token)});return <Container><Typography variant='h4'>Admin Login</Typography><Stack gap={1} sx={{maxWidth:400}}><TextField label='Email' value={email} onChange={e=>setE(e.target.value)}/><TextField label='Password' type='password' value={password} onChange={e=>setP(e.target.value)}/><Button onClick={()=>m.mutate()} variant='contained'>Login</Button></Stack></Container>}

export const DashboardPage=()=> <Container><Typography variant='h4'>Dashboard</Typography><Typography>Shipping admin console.</Typography></Container>;

const Loading=()=> <Box sx={{py:4,textAlign:'center'}}><CircularProgress/></Box>;
const Empty=({text}:{text:string})=> <Alert severity='info'>{text}</Alert>;

export const CustomersPage=()=>{const qc=useQueryClient();const [name,setName]=useState('');const [phone,setPhone]=useState('');const {data,isLoading}=useQuery({queryKey:['customers'],queryFn:()=>api.get('/api/customers').then(r=>r.data)});const add=useMutation({mutationFn:()=>api.post('/api/customers',{customerRef:`C${Date.now()}`,name,primaryPhone:phone,email:null,isActive:true}),onSuccess:()=>{setName('');setPhone('');qc.invalidateQueries({queryKey:['customers']});}});if(isLoading) return <Loading/>;return <Container><Typography variant='h4'>Customers</Typography><Stack direction='row' gap={1} sx={{my:2}}><TextField size='small' label='Name' value={name} onChange={e=>setName(e.target.value)}/><TextField size='small' label='Phone' value={phone} onChange={e=>setPhone(e.target.value)}/><Button variant='contained' onClick={()=>add.mutate()}>Add</Button></Stack>{!data?.length?<Empty text='No customers'/>:<Table><TableHead><TableRow><TableCell>Ref</TableCell><TableCell>Name</TableCell><TableCell>Phone</TableCell></TableRow></TableHead><TableBody>{data.map((c:any)=><TableRow key={c.id}><TableCell>{c.customerRef}</TableCell><TableCell>{c.name}</TableCell><TableCell>{c.primaryPhone}</TableCell></TableRow>)}</TableBody></Table>}<GroupExportCard/></Container>}

export const SimpleListPage=({title,endpoint}:{title:string;endpoint:string})=>{const {data,isLoading}=useQuery({queryKey:[endpoint],queryFn:()=>api.get(endpoint).then(r=>r.data)});return <Container><Typography variant='h4'>{title}</Typography>{isLoading?<Loading/>:(!data?.length?<Empty text={`No ${title.toLowerCase()}`}/>:<Paper sx={{p:2}}><pre>{JSON.stringify(data,null,2)}</pre></Paper>)}</Container>};

export const ShipmentsPage=()=>{const qc=useQueryClient();const {data,isLoading}=useQuery({queryKey:['shipments'],queryFn:()=>api.get('/api/shipments').then(r=>r.data)});const [gate,setGate]=useState<any>();const transit=useMutation({mutationFn:({id,action}:{id:number;action:string})=>api.post(`/api/shipments/${id}/${action}`),onSuccess:()=>qc.invalidateQueries({queryKey:['shipments']}),onError:(e)=>setGate(parseApiError(e))});if(isLoading) return <Loading/>;return <Container><Typography variant='h4'>Shipments</Typography>{gate?.code==='PHOTO_GATE_FAILED'&&<Alert severity='error'>{gate.message}<Table><TableHead><TableRow><TableCell>Package</TableCell><TableCell>Customer</TableCell><TableCell>Stage</TableCell></TableRow></TableHead><TableBody>{gate.missing?.map((m:any)=><TableRow key={m.packageId}><TableCell><Link href={`/packages/${m.packageId}`}>{m.packageId}</Link></TableCell><TableCell>{m.customerRef}</TableCell><TableCell>{m.stage}</TableCell></TableRow>)}</TableBody></Table></Alert>}{!data?.length?<Empty text='No shipments'/>:<Table><TableHead><TableRow><TableCell>ID</TableCell><TableCell>RefCode</TableCell><TableCell>Status</TableCell><TableCell>Actions</TableCell></TableRow></TableHead><TableBody>{data?.map((s:any)=><TableRow key={s.id}><TableCell>{s.id}</TableCell><TableCell>{s.refCode}</TableCell><TableCell>{s.status}</TableCell><TableCell><Button onClick={()=>transit.mutate({id:s.id,action:'depart'})}>Depart</Button><Button onClick={()=>transit.mutate({id:s.id,action:'close'})}>Close</Button></TableCell></TableRow>)}</TableBody></Table>}</Container>}

export const PackageDetailPage=({id}:{id:string})=>{const {data,isLoading}=useQuery({queryKey:['pkg',id],queryFn:()=>api.get(`/api/packages/${id}`).then(r=>r.data)});const [gate,setGate]=useState<any>();const m=useMutation({mutationFn:()=>api.post(`/api/packages/${id}/handout`),onError:(e)=>setGate(parseApiError(e))});if(isLoading) return <Loading/>;const media=data?.media||data?.package?.media||[];return <Container><Typography variant='h4'>Package {id}</Typography>{gate?.code==='PHOTO_GATE_FAILED'&&<Alert severity='error'>{gate.message}</Alert>}<Button onClick={()=>m.mutate()}>Handout</Button><PhotoGallery media={media}/></Container>}

export const MessagingLogsPage=()=>{const {data,isLoading}=useQuery({queryKey:['msg-logs'],queryFn:()=>api.get('/api/whatsapp/campaigns').then(r=>r.data)});if(isLoading) return <Loading/>;return <Container><Typography variant='h4'>Messaging Logs</Typography>{!data?.length?<Empty text='No campaigns'/>:<Table><TableHead><TableRow><TableCell>ID</TableCell><TableCell>Type</TableCell><TableCell>Recipients</TableCell><TableCell>Completed</TableCell></TableRow></TableHead><TableBody>{data.map((c:any)=><TableRow key={c.id}><TableCell>{c.id}</TableCell><TableCell>{c.type}</TableCell><TableCell>{c.recipientCount}</TableCell><TableCell>{String(c.completed)}</TableCell></TableRow>)}</TableBody></Table>}</Container>}

export const GroupExportCard=()=>{const m=useMutation({mutationFn:(format:string)=>api.post('/api/exports/group-helper',{format}),onSuccess:(r)=>window.open(r.data.publicUrl,'_blank')});return <Box sx={{mt:2}}><Alert severity='warning'>WhatsApp groups reveal phone numbers to all members.</Alert><Button onClick={()=>m.mutate('csv')}>Export CSV</Button><Button onClick={()=>m.mutate('vcf')}>Export VCF</Button></Box>}
