import { Alert, Box, Button, Container, Link, Paper, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from '@mui/material';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { api, parseApiError } from '../api/client';
import { useState } from 'react';
import { PhotoGallery } from '../components/media/PhotoGallery';

export const LoginPage=()=>{const [email,setE]=useState('admin@local');const [password,setP]=useState('Admin123!');const m=useMutation({mutationFn:()=>api.post('/api/auth/login',{email,password}),onSuccess:(r)=>localStorage.setItem('token',r.data.token)});return <Container><Typography variant='h4'>Admin Login</Typography><TextField label='Email' value={email} onChange={e=>setE(e.target.value)}/><TextField label='Password' type='password' value={password} onChange={e=>setP(e.target.value)}/><Button onClick={()=>m.mutate()} variant='contained'>Login</Button></Container>}

export const DashboardPage=()=> <Container><Typography variant='h4'>Dashboard</Typography><Typography>Shipping admin console.</Typography></Container>;

export const SimpleListPage=({title,endpoint}:{title:string;endpoint:string})=>{const {data}=useQuery({queryKey:[endpoint],queryFn:()=>api.get(endpoint).then(r=>r.data)});return <Container><Typography variant='h4'>{title}</Typography><Paper><pre>{JSON.stringify(data,null,2)}</pre></Paper></Container>};

export const ShipmentsPage=()=>{const qc=useQueryClient();const {data}=useQuery({queryKey:['shipments'],queryFn:()=>api.get('/api/shipments').then(r=>r.data)});const [gate,setGate]=useState<any>();const transit=useMutation({mutationFn:({id,action}:{id:number;action:string})=>api.post(`/api/shipments/${id}/${action}`),onSuccess:()=>qc.invalidateQueries({queryKey:['shipments']}),onError:(e)=>setGate(parseApiError(e))});return <Container><Typography variant='h4'>Shipments</Typography>{gate?.code==='PHOTO_GATE_FAILED'&&<Alert severity='error'>{gate.message}<Table><TableHead><TableRow><TableCell>Package</TableCell><TableCell>Customer</TableCell><TableCell>Stage</TableCell></TableRow></TableHead><TableBody>{gate.missing?.map((m:any)=><TableRow key={m.packageId}><TableCell><Link href={`/packages/${m.packageId}`}>{m.packageId}</Link></TableCell><TableCell>{m.customerRef}</TableCell><TableCell>{m.stage}</TableCell></TableRow>)}</TableBody></Table></Alert>}<Table><TableHead><TableRow><TableCell>ID</TableCell><TableCell>RefCode</TableCell><TableCell>Status</TableCell><TableCell>Actions</TableCell></TableRow></TableHead><TableBody>{data?.map((s:any)=><TableRow key={s.id}><TableCell>{s.id}</TableCell><TableCell>{s.refCode}</TableCell><TableCell>{s.status}</TableCell><TableCell><Button onClick={()=>transit.mutate({id:s.id,action:'depart'})}>Depart</Button><Button onClick={()=>transit.mutate({id:s.id,action:'close'})}>Close</Button></TableCell></TableRow>)}</TableBody></Table></Container>}

export const PackageDetailPage=({id}:{id:string})=>{const {data}=useQuery({queryKey:['pkg',id],queryFn:()=>api.get(`/api/packages/${id}`).then(r=>r.data)});const [gate,setGate]=useState<any>();const m=useMutation({mutationFn:()=>api.post(`/api/packages/${id}/handout`),onError:(e)=>setGate(parseApiError(e))});return <Container><Typography variant='h4'>Package {id}</Typography>{gate?.code==='PHOTO_GATE_FAILED'&&<Alert severity='error'>{gate.message}</Alert>}<Button onClick={()=>m.mutate()}>Handout</Button><PhotoGallery media={data?.media||[]}/></Container>}

export const GroupExportCard=()=>{const m=useMutation({mutationFn:(format:string)=>api.post('/api/exports/group-helper',{format}),onSuccess:(r)=>window.open(r.data.publicUrl,'_blank')});return <Box><Alert severity='warning'>WhatsApp groups reveal phone numbers to all members.</Alert><Button onClick={()=>m.mutate('csv')}>Export CSV</Button><Button onClick={()=>m.mutate('vcf')}>Export VCF</Button></Box>}
