using System.ComponentModel.DataAnnotations;

namespace ShippingPlatform.Api.Models;

public class AdminUser { public int Id { get; set; } [MaxLength(200)] public string Email { get; set; } = string.Empty; public string PasswordHash { get; set; } = string.Empty; public bool IsActive { get; set; } = true; public DateTime? LastLoginAt { get; set; } }
public class Customer { public int Id { get; set; } [MaxLength(200)] public string Name { get; set; } = string.Empty; [MaxLength(30)] public string PrimaryPhone { get; set; } = string.Empty; [MaxLength(200)] public string? Email { get; set; } public bool IsActive { get; set; } = true; public WhatsAppConsent? WhatsAppConsent { get; set; } }
public class WhatsAppConsent { [Key] public int CustomerId { get; set; } public bool OptInStatusUpdates { get; set; } = true; public bool OptInDeparturePhotos { get; set; } = true; public bool OptInArrivalPhotos { get; set; } = true; public DateTime? OptedOutAt { get; set; } public Customer Customer { get; set; } = null!; }
public class Warehouse { public int Id { get; set; } [MaxLength(3)] public string Code { get; set; } = string.Empty; [MaxLength(200)] public string Name { get; set; } = string.Empty; public string City { get; set; } = string.Empty; public string Country { get; set; } = string.Empty; public decimal MaxWeightKg { get; set; } public decimal MaxVolumeM3 { get; set; } public bool IsActive { get; set; } = true; }
public class PricingConfig { public int Id { get; set; } public string Name { get; set; } = string.Empty; public string Currency { get; set; } = "EUR"; public DateTime EffectiveFrom { get; set; } public DateTime? EffectiveTo { get; set; } public decimal DefaultRatePerKg { get; set; } public decimal DefaultRatePerM3 { get; set; } public PricingConfigStatus Status { get; set; } = PricingConfigStatus.Draft; }
public class GoodType { public int Id { get; set; } public string NameEn { get; set; } = string.Empty; public string NameAr { get; set; } = string.Empty; public decimal? RatePerKg { get; set; } public decimal? RatePerM3 { get; set; } public bool IsActive { get; set; } = true; }

public class Shipment { public int Id { get; set; } public string RefCode { get; set; } = string.Empty; [MaxLength(4)] public string? TiiuCode { get; set; } public int OriginWarehouseId { get; set; } public int DestinationWarehouseId { get; set; } public Warehouse OriginWarehouse { get; set; } = null!; public Warehouse DestinationWarehouse { get; set; } = null!; public DateTime PlannedDepartureDate { get; set; } public DateTime PlannedArrivalDate { get; set; } public DateTime? ActualDepartureAt { get; set; } public DateTime? ActualArrivalAt { get; set; } public ShipmentStatus Status { get; set; } = ShipmentStatus.Draft; public decimal MaxWeightKg { get; set; } = 0; public decimal MaxVolumeM3 { get; set; } = 0; public decimal TotalWeightKg { get; set; } public decimal TotalVolumeM3 { get; set; } public string? ExternalTrackingCode { get; set; } public string? ExternalCarrierName { get; set; } public string? ExternalOrigin { get; set; } public string? ExternalDestination { get; set; } public DateTime? ExternalEstimatedArrivalAt { get; set; } public string? ExternalStatus { get; set; } public DateTime? ExternalLastSyncedAt { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public List<Package> Packages { get; set; } = []; }
public class ShipmentSequence { public int Id { get; set; } [MaxLength(3)] public string OriginWarehouseCode { get; set; } = string.Empty; public int Year { get; set; } public int LastNumber { get; set; } }
public class Package { public int Id { get; set; } public int ShipmentId { get; set; } public Shipment Shipment { get; set; } = null!; public int CustomerId { get; set; } public Customer Customer { get; set; } = null!; public ProvisionMethod ProvisionMethod { get; set; } = ProvisionMethod.CustomerProvided; public PackageStatus Status { get; set; } = PackageStatus.Draft; public decimal TotalWeightKg { get; set; } public decimal TotalVolumeM3 { get; set; } public string Currency { get; set; } = "EUR"; public decimal AppliedRatePerKg { get; set; } public decimal AppliedRatePerM3 { get; set; } public decimal ChargeAmount { get; set; } public bool HasDeparturePhotos { get; set; } public bool HasArrivalPhotos { get; set; } public bool HasPricingOverride { get; set; } public int? SupplyOrderId { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public List<PackageItem> Items { get; set; } = []; public List<Media> Media { get; set; } = []; public List<PackagePricingOverride> PricingOverrides { get; set; } = []; }
public class PackageItem { public int Id { get; set; } public int PackageId { get; set; } public Package Package { get; set; } = null!; public int GoodTypeId { get; set; } public GoodType GoodType { get; set; } = null!; public int Quantity { get; set; } public decimal WeightKg { get; set; } public decimal VolumeM3 { get; set; } public decimal LineCharge { get; set; } }
public class Supplier { public int Id { get; set; } public string Name { get; set; } = string.Empty; public string? Email { get; set; } public bool IsActive { get; set; } = true; }
public class SupplyOrder { public int Id { get; set; } public int CustomerId { get; set; } public Customer Customer { get; set; } = null!; public int SupplierId { get; set; } public Supplier Supplier { get; set; } = null!; public int? PackageId { get; set; } public string Name { get; set; } = string.Empty; public decimal PurchasePrice { get; set; } public string? Details { get; set; } public SupplyOrderStatus Status { get; set; } = SupplyOrderStatus.Draft; public string? CancelReason { get; set; } }
public class Media { public int Id { get; set; } public int PackageId { get; set; } public Package Package { get; set; } = null!; public MediaStage Stage { get; set; } public string BlobKey { get; set; } = string.Empty; public string PublicUrl { get; set; } = string.Empty; public string? Notes { get; set; } public DateTime? CapturedAt { get; set; } public DateTime UploadedAt { get; set; } = DateTime.UtcNow; public int RecordedByAdminUserId { get; set; } public string? OperatorName { get; set; } }
public class WhatsAppCampaign { public int Id { get; set; } public CampaignType Type { get; set; } public int ShipmentId { get; set; } public int TriggeredByAdminUserId { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public int RecipientCount { get; set; } public bool Completed { get; set; } public List<WhatsAppDeliveryLog> DeliveryLogs { get; set; } = []; }
public class WhatsAppDeliveryLog { public int Id { get; set; } public int CampaignId { get; set; } public WhatsAppCampaign Campaign { get; set; } = null!; public int CustomerId { get; set; } public string Phone { get; set; } = string.Empty; public DeliveryResult Result { get; set; } public string? FailureReason { get; set; } public DateTime? SentAt { get; set; } }
public class PackagePricingOverride { public int Id { get; set; } public int PackageId { get; set; } public Package Package { get; set; } = null!; public PricingOverrideType OverrideType { get; set; } public decimal OriginalValue { get; set; } public decimal NewValue { get; set; } [MaxLength(500)] public string Reason { get; set; } = string.Empty; public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public int AdminUserId { get; set; } }
